# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-04 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(null=True),
        ),
    ]
