# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=news.models.generate_filename),
        ),
    ]
